### ISSUE TITLE
Upgrade axios to 0.21.1 or later version

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw-repo#1]
| verifiablesoftware/vsw-repo
-- | --
Known high severity security vulnerability detected in axios < 0.21.1 defined in package-lock.json.package-lock.json update suggested: axios ~> 0.21.1.Always verify the validity and compatibility of suggestions with your codebase. | Known high severity security vulnerability detected in axios < 0.21.1 defined in package-lock.json. | package-lock.json update suggested: axios ~> 0.21.1. | Always verify the validity and compatibility of suggestions with your codebase.
Known high severity security vulnerability detected in axios < 0.21.1 defined in package-lock.json.
package-lock.json update suggested: axios ~> 0.21.1.
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by TonWolting** [comment]
@tervoju as axios is node.js dependency please check and update to latest version. Release 0.21.1 (release date December 20th, 2020) should fix this. Thanks

**Comment by tervoju** [comment]
updated
